name: rov
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.6.1=hb765f3a_0
  - bidict=0.23.1=py311hca03da5_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h2ca31fc_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - cyrus-sasl=2.1.28=h0121217_3
  - dav1d=1.2.1=h80987f9_0
  - dbus=1.16.2=hda038a8_0
  - eigen=3.4.0=h48ca7d4_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=6.1.1=h7693a39_3
  - fluidsynth=2.3.7=h80fea77_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h29935d0_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h9bcf4fe_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - gflags=2.2.2=h313beb8_1
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.2=hc880cf1_0
  - glib-tools=2.84.2=hc880cf1_0
  - glog=0.5.0=h313beb8_1
  - graphite2=1.3.14=hc377ac9_1
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - gstreamer-orc=0.4.41=hdbbdb2f_0
  - h11=0.16.0=py311hca03da5_0
  - harfbuzz=10.2.0=he637ebf_1
  - hdf5=1.14.5=hd77251f_2
  - icu=73.1=h313beb8_0
  - jpeg=9f=h2f69dba_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he93ba84_0
  - leptonica=1.82.0=h18c3764_2
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libarchive=3.8.1=h44a83c5_0
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libavif=0.11.1=h80987f9_0
  - libcurl=8.15.0=hcdd2897_0
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libevent=2.1.12=h02f6b3c_1
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.3=hb765f3a_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libkrb5=1.21.3=h73ed823_4
  - libmad=0.15.1b=h1a8c8d9_1001
  - libnghttp2=1.57.0=h62f6fdd_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.39=h80987f9_0
  - libpq=17.4=h6b53c48_2
  - libprotobuf=5.29.3=h14f15fd_1
  - librsvg=2.56.3=h38920c8_2
  - libsndfile=1.2.2=h9739721_1
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h3e2b118_0
  - libtheora=1.1.1=h99b78c6_1006
  - libtiff=4.5.1=hc9ead59_1
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lmdb=0.9.31=h79febb2_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpg123=1.32.9=hf642e45_0
  - mysql=8.4.0=h065ec36_2
  - ncurses=6.5=hee39554_0
  - numpy=2.3.3=py311hc95ac1c_1
  - numpy-base=2.3.3=py311h8087a70_1
  - opencv=4.10.0=py311h2860021_4
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.0=hbc2ba62_2
  - openldap=2.6.10=h6d5b105_1
  - openssl=3.5.4=h5503f6c_0
  - opusfile=0.12=h5643135_2
  - pango=1.50.7=hf2328af_2
  - pcre2=10.42=hb066dcc_1
  - pillow=11.1.0=py311h84e58ab_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - portaudio=19.6.0=h13dd4ca_9
  - portmidi=2.0.6=h286801f_0
  - pygame=2.2.0=py311haad0d3d_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.11=h89a136b_0_cpython
  - python-engineio=4.12.2=py311hca03da5_0
  - python-socketio=5.13.0=py311hca03da5_0
  - python_abi=3.11=8_cp311
  - qrcode=8.2=py311hca03da5_0
  - qtbase=6.7.3=h89abe44_4
  - readline=8.3=h0b18652_0
  - rich=14.2.0=pyhcf101f3_0
  - sdl2=2.32.56=h248ca61_0
  - sdl2_image=2.6.3=hb71b326_0
  - sdl2_mixer=2.6.3=h4fe3bdc_1
  - sdl2_ttf=2.24.0=h443c5de_0
  - sdl3=3.2.24=h919df07_0
  - setuptools=80.9.0=py311hca03da5_0
  - simple-websocket=1.1.0=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - wsproto=1.2.0=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - imagezmq==1.2.0
      - pyzmq==27.1.0
prefix: /opt/anaconda3/envs/rov
