name: rov
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom 
  - bidict 
  - blas 
  - bzip2 
  - c-ares 
  - ca-certificates 
  - cairo 
  - cyrus-sasl 
  - dav1d 
  - dbus 
  - eigen 
  - expat 
  - ffmpeg 
  - fluidsynth 
  - font-ttf-dejavu-sans-mono 
  - font-ttf-inconsolata 
  - font-ttf-source-code-pro 
  - font-ttf-ubuntu 
  - fontconfig 
  - fonts-conda-ecosystem 
  - fonts-conda-forge 
  - freetype 
  - fribidi 
  - gdk-pixbuf 
  - gettext 
  - gettext-tools 
  - gflags 
  - giflib 
  - glib 
  - glib-tools 
  - glog 
  - graphite2 
  - gst-plugins-base 
  - gstreamer 
  - gstreamer-orc 
  - h11 
  - harfbuzz 
  - hdf5 
  - icu 
  - jpeg 
  - lame 
  - lcms2 
  - leptonica 
  - lerc 
  - libabseil 
  - libarchive 
  - libasprintf 
  - libasprintf-devel 
  - libavif 
  - libcurl 
  - libcxx 
  - libdeflate 
  - libedit 
  - libev 
  - libevent 
  - libexpat 
  - libffi 
  - libflac 
  - libgettextpo 
  - libgettextpo-devel 
  - libgfortran 
  - libgfortran5 
  - libglib 
  - libiconv 
  - libintl 
  - libintl-devel 
  - libkrb5 
  - libmad 
  - libnghttp2 
  - libogg 
  - libopenblas 
  - libopus 
  - libpng 
  - libpq 
  - libprotobuf 
  - librsvg 
  - libsndfile 
  - libsodium 
  - libsqlite 
  - libssh2 
  - libtheora 
  - libtiff 
  - libusb 
  - libvorbis 
  - libvpx 
  - libvulkan-loader 
  - libwebp 
  - libwebp-base 
  - libxml2 
  - libzlib 
  - llvm-openmp 
  - lmdb 
  - lz4-c 
  - markdown-it-py 
  - mdurl 
  - mpg123 
  - mysql 
  - ncurses 
  - numpy 
  - numpy-base 
  - opencv 
  - openh264 
  - openjpeg 
  - openldap 
  - openssl 
  - opusfile 
  - pango 
  - pcre2 
  - pillow 
  - pip 
  - pixman 
  - portaudio 
  - portmidi 
  - pygame 
  - pygments 
  - python 
  - python-engineio 
  - python-socketio 
  - python_abi 
  - qrcode 
  - qtbase 
  - readline 
  - rich 
  - sdl2 
  - sdl2_image 
  - sdl2_mixer 
  - sdl2_ttf 
  - sdl3 
  - setuptools 
  - simple-websocket 
  - sqlite 
  - tesseract 
  - tk 
  - typing_extensions 
  - tzdata 
  - wheel 
  - wsproto 
  - xz 
  - zlib 
  - zstd 
  - pip:
      - imagezmq 
      - pyzmq 
prefix: /opt/anaconda3/envs/rov
